src/objects/ErrorLog__c.object
<CustomObject>
    <fields>
        <fullName>ErrorCode__c</fullName>
        <description>Error Code</description>
        <label>Error Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ErrorMessage__c</fullName>
        <description>The error message</description>
        <label>Error Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ErrorLog-{0000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Image__c.object
<CustomObject>
    <description>Object for storing images retrieved from the Image API</description>
    <fields>
        <fullName>ImageApiId__c</fullName>
        <description>Id from the Image API</description>
        <externalId>true</externalId>
        <label>ImageApiId</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ImageTitle__c</fullName>
        <description>Image title from the Image API</description>
        <label>Image Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ImageUrl__c</fullName>
        <description>Image Url from the Image API, used as External Id</description>
        <label>Image Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Image</label>
    <nameField>
        <displayFormat>Image-{0000}</displayFormat>
        <label>Image</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Images</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SearchImagesController.cls
/**
* Apex Controller for the searchImages Lightning Web Component
 */
public with sharing class SearchImagesController {

    @AuraEnabled(Cacheable = true)
    public static List<Image__c> fetchImages(String imageTitle) {
        imageTitle = '%' + imageTitle + '%';
        List<Image__c> images = new List<Image__c>();
        images = [
            SELECT  Id, Name, ImageTitle__c, ImageApiId__c, ImageUrl__c
            FROM Image__c
            WHERE ImageTitle__c LIKE :imageTitle
        ];
        if(images.isEmpty()) {
            throw new AuraHandledException(Label.NoRecordsFound);
        }
        return images;
    }

    @AuraEnabled
    public static void sendMailToUser(String emailAddress, List<Image__c> images) {
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        message.toAddresses = new List<String>{emailAddress};
        message.subject = Constants.IMAGES_EMAIL_SUBJECT;

        for(Integer i = 0; i < images.size(); i++) {
            message.plainTextBody += String.valueOf(i+1) + ') Image Name: ' + images[i].Name + ', Image URL: ' + images[i].ImageUrl__c + '\n';
        }

        Messaging.SingleEmailMessage[] messages = new List<Messaging.SingleEmailMessage>{message};
        try {
            Messaging.sendEmail(messages);
        } catch (Exception ex) {
            insert new ErrorLog__c(
                ErrorCode__c = Constants.ERROR_LOG_EMAIL_SERVICE_ERROR,
                ErrorMessage__c = ex.getMessage()
            );
            throw new CustomException(ex.getMessage());
        }
    }
}