src/objects/Image__c.object
<CustomObject>
    <description>Object for storing images retrieved from the Image API</description>
    <fields>
        <fullName>AlbumId__c</fullName>
        <description>Image Id from the Image API</description>
        <label>AlbumId</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ImageApiId__c</fullName>
        <description>Id from the Image API</description>
        <externalId>true</externalId>
        <label>ImageApiId</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ImageTitle__c</fullName>
        <description>Image title from the Image API</description>
        <label>Image Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ImageUrl__c</fullName>
        <description>Image Url from the Image API, used as External Id</description>
        <label>Image Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ThumbnailUrl__c</fullName>
        <description>Thumbnail url from the Image API</description>
        <label>Thumbnail Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Image</label>
    <nameField>
        <displayFormat>Image-{0000}</displayFormat>
        <label>Image</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Images</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IntegrationEndpoint__mdt.object
<CustomObject>
    <description>Used to configure integrations</description>
    <fields>
        <fullName>EndpointAddress__c</fullName>
        <description>Address of the integration endpoint</description>
        <label>Endpoint Address</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsLogActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox indicating whether an integration log will be saved for the integration.</description>
        <label>IsLogActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Integration Endpoint</label>
    <pluralLabel>Integration Endpoints</pluralLabel>
</CustomObject>

src/objects/IntegrationLog__c.object
<CustomObject>
    <description>Object for storing integration logs</description>
    <fields>
        <fullName>CommunicationTime__c</fullName>
        <description>Time of the communication between services</description>
        <label>Communication Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ErrorOccurred__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox indicating whether an error has occurred in the communication.</description>
        <label>Error Occurred</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RequestMessage__c</fullName>
        <description>Request message</description>
        <label>Request Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ResponseMessage__c</fullName>
        <description>Response message</description>
        <label>Response Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IntegrationLog-{0000}</displayFormat>
        <label>Integration Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ImageApiService.cls
/**
* Class implementing communication with the Image API
 */
public class ImageApiService {

    public static final IntegrationEndpoint__mdt IMAGE_API_INTEGRATION_ENDPOINT = Utils.getIntegrationEndpoint(
        Constants.IMAGE_API_INTEGRATION_ENDPOINT
    );

    public class PhotosCallout {
        private HttpRequest request;
        private Http httpInitiation;
        private Boolean isException = false;

        public PhotosCallout() {
            this.httpInitiation = new Http();
            this.request = new HttpRequest();
            this.request.setHeader(Constants.CONTENT_TYPE, Constants.CONTENT_TYPE_APP_JSON);
            this.request.setMethod(Constants.REQUEST_GET_METHOD);
            this.request.setEndpoint(IMAGE_API_INTEGRATION_ENDPOINT.EndpointAddress__c);
        }

        /**
        *  Method sending the HTTP request
        * @return HTTPResponse
        */
        public HTTPResponse sendRequest() {
            HTTPResponse response = this.httpInitiation.send(request);
            if (response.getStatusCode() != Constants.API_SUCCESS_CODE && response.getStatusCode() != Constants.API_BAD_REQUEST_CODE) {
                isException = true;
            }

            if (IMAGE_API_INTEGRATION_ENDPOINT.IsLogActive__c) {
                saveIntegrationLog(response);
            }

            return response;
        }

        private void saveIntegrationLog(HTTPResponse response) {
            insert new IntegrationLog__c(
                RequestMessage__c = request.getBody(),
                ResponseMessage__c = response.getBody().substring(0, Constants.TEXT_AREA_LONG_SIZE - 1),
                CommunicationTime__c = System.now(),
                ErrorOccurred__c = isException
            );
        }

    }

    /**
    *  Method fetching photos from the Image API
    */
    public static void fetchPhotos() {
        PhotosCallout callout = new PhotosCallout();
        List<ImageApiJsonParser> parsedImages = ImageApiJsonParser.parse(callout.sendRequest().getBody());
        insertImages(JSON.serialize(parsedImages));
    }

    @future
    private static void insertImages(String imagesJson) {
        List<ImageApiJsonParser> parsedImages = (List<ImageApiJsonParser>) JSON.deserialize(
            imagesJson, List<ImageApiJsonParser>.class
        );

        List<Image__c> imagesToInsert = new List<Image__c>();
        for(ImageApiJsonParser imageParser : parsedImages) {
            imagesToInsert.add(
                new Image__c(
                    ImageApiId__c = imageParser.id,
                    AlbumId__c = imageParser.albumId,
                    ImageUrl__c = imageParser.url,
                    ImageTitle__c = imageParser.title,
                    ThumbnailUrl__c = imageParser.thumbnailUrl
                )
            );
        }
        insert imagesToInsert;
        //add database.upsert here and error handling
    }
}